
image: golang:latest
variables:
  REPO_NAME: gitlab.com/sorcero/community/dgbrx

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
  - test
  - build
  - deploy
  - release

format:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  script:
    - cd cmd/dgbrx
    - go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/dgbrx
  artifacts:
    paths:
      - dgbrx


release:
  stage: release
  image:
    name: goreleaser/goreleaser
    entrypoint: ['']
  only:
    - tags
  variables:
    # Disable shallow cloning so that goreleaser can diff between tags to
    # generate a changelog.
    GIT_DEPTH: 0
  script:
    - goreleaser release --rm-dist
